default_language_version:
    python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the ref you want to point at
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: ["--branch", "main"]  # main protected by default if not specified
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  # # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
  # - repo: https://github.com/psf/black-pre-commit-mirror
  #   rev: 23.11.0
  #   hooks:
  #     - id: black
  #       # It is recommended to specify the latest version of Python
  #       # if pre-commit's default_language_version not specified
  #       args: ["--line-length=88"]

  # - repo: https://github.com/pycqa/isort
  #   rev: 5.12.0
  #   hooks:
  #     - id: isort
  #       args: ["--profile", "black", "--filter-files"]

  # - repo: https://github.com/pycqa/flake8
  #   rev: 6.0.0
  #   hooks:
  #     - id: flake8
  #       args: ["--max-line-length=88"]
