FROM --platform=$BUILDPLATFORM python:3.10.12-alpine AS build

# Checkout and install dagster libraries needed to run the gRPC server
# exposing your repository to dagster-webserver and dagster-daemon, and to load the DagsterInstance

RUN pip install --upgrade pip
RUN pip install \
    dagster==1.5.10  \
    dagster-postgres \
    dagster-docker \
    grpcio==1.57.0

# Add repository code
WORKDIR /opt/dagster/app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY energy_analyzer ./energy_analyzer

# Run dagster gRPC server on port 4000

EXPOSE 4000

# CMD allows this to be overridden from run launchers or executors that want
# to run other commands against your repository
CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000",  "-f", "energy_analyzer/app.py"]
