# Dagster libraries to run both dagster-webserver and the dagster-daemon. Does not
# need to have access to any pipeline code.

FROM --platform=$BUILDPLATFORM python:3.10.12-alpine AS build

RUN pip install \
    dagster==1.5.10 \
    dagster-graphql==1.5.10 \
    dagster-webserver==1.5.10 \
    dagster-postgres \
    dagster-docker \
    grpcio==1.57.0

# Set $DAGSTER_HOME and copy dagster instance and workspace YAML there
ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME

COPY dagster.yaml workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME
